<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script>
    $(function() {
      $("#accordion").accordion({
        active: parseInt(getAnchor(location.href)),
        heightStyle: "content"
      });
    });
    
    function getAnchor(url)
    {
      var index = url.lastIndexOf('#');
      if (index != -1)
        return url.substring(index+1);
    }
    
    function checkForm(oForm) {
      var filled = 0;
      for (var i = 0; i < oForm.elements.length; i++) {
        if (GetElementValue(oForm.elements[i]).length > 0)
          filled++;
      }
      if(filled!=oForm.elements.length) {
        alert("Please Fill Form Completely");
        return false;
      }
    }

    function GetElementValue(element) {
      if ((element.type === "checkbox" || element.type === "radio") && 
           element.checked === false)
        return "";
      return element.value;
    }
  </script>
</head>
<body>

	<%
		String mgAccount = session.getAttribute("account").toString();
		out.print( "<p class='message' > Welcome! Dear " + mgAccount + "</p>");
	%>
<h2>Revenue Reports</h2>
<div id="accordion">
  <h3>Revenue Summary</h3>
  <div class="content">
    <p>
      Produce a summary listing of revenue generated by a particular flight, 
      destination city, or customer
    </p>
    <form name="summbyflight" action="revenueSummaryByFlight.jsp" method="post">
      Flight Number: <input class="textbox" type="text" value="CA819" name="summFlightNumber">
      <button value="dummy" type="submit">Query</button>
    </form>
    <br>or<br>
    <form name="summbycity" action="revenueSummaryByCity.jsp" method="post">
     Destination City: <input class="textbox" type="text" value= "BEIJING" name="summCityName">
      <button value="dummy" type="submit">Query</button>
    </form>
    <br>or<br>
    <form name="summbycust" action="revenueSummaryByCustomer.jsp" method="post">
    Customer's First Name: <input class="textbox" type="text" value="JINGYI" name="firstName"/><br>
    Customer's Last Name: <input class="textbox" type="text" value="GU" name="lastName"/>
      <button value="dummy" type="submit">Query</button>
    </form>
  </div>
  
  <h3>Top Customer</h3>
  <div class="content">
    <p>
      Determine which customer generated most total revenue
    </p>
    <form name="cotm" action="revenueTopCustomer.jsp" method="post">
      <button value="dummy" type="submit">Query</button>
    </form>
  </div>
</div>
</body>
</html>
